### ISSUE TITLE
Can't be opened on MacOS

### ISSUE THREAD

**Issue by troy-lamerton** [rbreu/beeref#18]
I would like to try BeeRef, but MacOS blocks it from opening due to 'security'.

Reproduce steps:

- download latest release zip for Mac
- unzip
- there is no .app file, so open a terminal and launch `BeeRef-0.1.1` executable
- MacOS prevents it from running, so open Security & Privacy and click 'Allow anyway'
- launch `BeeRef-0.1.1` executable again
- a new 'can't be opened' prompt appears:
![Screen Shot 2021-08-11 at 09 44 04](https://user-images.githubusercontent.com/13446008/128990023-b3cd1bb1-1278-491c-a55b-dd1a38a06996.png)

A package called `BeeRef.app` would be most convenient for Mac users. Is it possible to build BeeRef.app when making a release?

**Comment by andrsd** [comment]
I had the same problem. I worked around this by cloning the repo, setting up virtual env, pulling in the dependencies and building the .app bundle via pyinstaller. This will give you a bundle that you can run and since you built it, it won't complain about any security, signing, etc.

Also, the new version of BeeRef migrated to a single binary release which will make it much easier to deploy to users (the new version has not been released, yet)

If you decide to build the bundle yourself, the steps to build BeeRef are [here](https://github.com/rbreu/beeref/blob/main/CONTRIBUTING.rst). I like to use the virtual env for each application so that it doesn't change my global environment. After `cd beeref`, you would need to do:
```
python3 -m venv env
env/bin/activate
```
and then, continue with `pip install -e .`

After installing `requirements/dev.txt`, jump directly to the build application step.

**Comment by rbreu** [comment]
Yes, the next release will have a bundled executable, since PyInstaller supports PyQt6 now. I've made a test build of the current development version here, feel free to try:

https://www.dropbox.com/s/uu1k3edk2se3j7i/build-macos-10.15.zip?dl=0

The executable is missing the executable flag atm, so you have to set that yourself. I will fix that for the next release.

**Comment by rbreu** [comment]
The new executables are now released.
