### ISSUE TITLE
[feature] Resize large images to save disk space

### ISSUE THREAD

**Issue by muhuk** [rbreu/beeref#34]
Having the ability to drag and drop images is awesome. Having the ability to scale images within the app is also awesome. Sometimes I scale down a larger image and scale up a smaller image within beeref. It would be great if there was a command that downscale the actual image data as well.

**Comment by rbreu** [comment]
One reason the file sizes get so big is that currently, the images get saved as PNG data inside the bee file. PNG is great for being lossless and supporting transparency, but it does result in bigger files than JPG. I'm planning on enhance the embedding mechanism (for example embed JPG images as JPG data, maybe let the user also opt in to embed everything as JPG), that should already make file sizes smaller.

Plus I'm planning on a mode where images loaded from hard drive can be linked to instead of embedded into the bee file, for cases where people mainly want to manage images they already have saved somewhere.

But I'll keep this in mind as well.

**Comment by rbreu** [comment]
Commit 7bef122 introduces the option to store the images as PNG, JPG, or a default "best guess". This reduces bee file sizes a lot, so I'll close this issue for now.

This change will go out in the next release.

**Comment by muhuk** [comment]
Based on dates, I'm guessing this is not part of `0.3.0` release :(
